language: java

os:
  - osx
sudo: required

#dist: trusty

#addons:
 # apt:
  #  packages:
   # - gcc-multilib
    #- g++-multilib
    #- yasm
    #- mingw-w64
    #- gcc-mingw-w64
    #- gcc-mingw-w64-i686
    #- gcc-mingw-w64-x86-64
    #- g++-mingw-w64
    #- g++-mingw-w64-i686
    #- g++-mingw-w64-x86-64
    #- binutils-mingw-w64-i686
    #- binutils-mingw-w64-x86-64
before_install:
  - brew update
  - brew install automake fdk-aac lame libass libtool libvorbis libvpx opus sdl shtool texi2html theora wget x264 xvid yasm
  - yasm --version
  - curl http://apache.openmirror.de//ant/binaries/apache-ant-1.9.6-bin.tar.gz | tar -xz
  - sudo mkdir -p /usr/local
  - sudo cp -rf apache-ant-1.9.6 /usr/local/apache-ant
  - export PATH=/usr/local/apache-ant/bin:"$PATH"
  - ant -version
  - ant -f gdx-video-desktop/jni/build.xml
deploy:
  provider: releases
  api_key: $T
  file: "gdx-video-desktop/libs/gdx-video-desktop-natives.jar"
  skip_cleanup: true
  on:
    tags: true
