language: java

os:
  - osx
sudo: required

#dist: trusty

addons:
  apt:
    packages:
    - gcc-multilib
    - g++-multilib
    - yasm
    - mingw-w64
    - gcc-mingw-w64
    - gcc-mingw-w64-i686
    - gcc-mingw-w64-x86-64
    - g++-mingw-w64
    - g++-mingw-w64-i686
    - g++-mingw-w64-x86-64
    - binutils-mingw-w64-i686
    - binutils-mingw-w64-x86-64

before_install: ant -f gdx-video-desktop/jni/build.xml
deploy:
  provider: releases
  api_key: $T
  file: "gdx-video-desktop/libs/gdx-video-desktop-natives.jar"
  skip_cleanup: true
  on:
    tags: true
